apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: sa-frontend
      containers:
        - image: robertbotez/sentiment-analysis-frontend
          imagePullPolicy: Always
          name: sa-frontend
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sa-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sa-frontend
