apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic
  labels:
    app: sa-logic
spec:
  selector:
    matchLabels:
      app: sa-logic
  replicas: 3
  template:
    metadata:
      labels:
        app: sa-logic
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: sa-logic
      containers:
        - image: robertbotez/sentiment-analysis-logic
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: sa-logic
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sa-logic
