apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
  labels:
    app: sa-web-app
spec:
  selector:
    matchLabels:
      app: sa-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: sa-web-app
      containers:
      - image: robertbotez/sentiment-analysis-web-app
        imagePullPolicy: Always
        name: sa-web-app
        env:
          - name: SA_LOGIC_API_URL
            value: "http://sa-logic"
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: sa-web-app
spec:
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: sa-web-app
