- name: Setting up pre-requisites
  hosts: master, workers
  become: true
  gather_facts: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Setting up the system
      import_tasks:
        tasks/01_prereqs.yml
      when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"

- name: Setup Docker Swarm cluster
  hosts: master
  become: yes
  gather_facts: true
  vars_files:
      - vars/main.yml
  tasks:
    - name: Configure master node
      import_tasks:
        tasks/02_swarm_master.yml
      when: not kubernetes.flag


- name: Join worker nodes to the Swarm cluster
  hosts: workers
  gather_facts: true
  become: yes
  vars_files:
       - vars/main.yml
  tasks:
    - name: Configure worker nodes
      import_tasks:
        tasks/03_swarm_workers.yml
      when: not kubernetes.flag

- name: Setting up control plane
  hosts: master
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: Setting up control plane
      import_tasks:
        tasks/03b_control_plane.yml
      when: kubernetes.flag | bool == true
      # when: not kubernetes.ha

#
- name: Setting up worker nodes
  hosts: workers
  become: true
  tasks:
    - name: Setting up control plane
      import_tasks:
        tasks/03b_worker_node.yml
      when: kubernetes.flag | bool == true
