route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'email'
  email_configs:
  - to: 'demoairportlabs@gmail.com'
    from: 'demoairportlabs@gmail.com' 
    smarthost: smtp.gmail.com:587
    auth_username: 'demoairportlabs@gmail.com'
    auth_identity: 'demoairportlabs@gmail.com'
    auth_password: 'rwoxyttpsznykehs'
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
