global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093 #alertmanager address 
rule_files:
  - alert_rules.yml
scrape_configs:
        #- job_name: 'prometheus'
        #static_configs:
        #    - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - master1:9100
        - worker1:9100
        - worker2:9100
  - job_name: 'docker'
    static_configs:
      - targets:
        - master1:9323
        - worker1:9323
        - worker2:9323
  - job_name: 'Pushgateway'
    honor_labels: true
    static_configs:
      - targets:
        - master1:9091
        - worker1:9091
        - worker2:9091 
  - job_name: blackbox # To get metrics about the exporter itself
    metrics_path: /metrics
    static_configs:
      - targets:
        - master1:9115
        - worker1:9115
        - worker2:9115
  - job_name: 'cadvisor'
    static_configs:
    - targets:
      - master1:8080
      - worker1:8080
      - worker2:8080
